export const GET_ALL_GROUP_REQUEST = 'GET_ALL_GROUP_REQUEST'
export const GET_ALL_GROUP_SUCCESS = 'GET_ALL_GROUP_SUCCESS'
export const GET_ALL_GROUP_FAIL = 'GET_ALL_GROUP_FAIL'

export const ADD_GROUP_REQUEST = 'ADD_GROUP_REQUEST'
export const ADD_GROUP_SUCCESS = 'ADD_GROUP_SUCCESS'
export const ADD_GROUP_FAIL = 'ADD_GROUP_FAIL'
export const ADD_GROUP_RESET = 'ADD_GROUP_RESET'

export const GET_SINGLE_GROUP_REQUEST = 'GET_SINGLE_GROUP_REQUEST'
export const GET_SINGLE_GROUP_SUCCESS = 'GET_SINGLE_GROUP_SUCCESS'
export const GET_SINGLE_GROUP_FAIL = 'GET_SINGLE_GROUP_FAIL'

export const DELETE_GROUP_REQUEST = 'DELETE_GROUP_REQUEST'
export const DELETE_GROUP_SUCCESS = 'DELETE_GROUP_SUCCESS'
export const DELETE_GROUP_FAIL = 'DELETE_GROUP_FAIL'
export const DELETE_GROUP_RESET = 'DELETE_GROUP_RESET'

export const UPDATE_GROUP_REQUEST = 'UPDATE_GROUP_REQUEST'
export const UPDATE_GROUP_SUCCESS = 'UPDATE_GROUP_SUCCESS'
export const UPDATE_GROUP_FAIL = 'UPDATE_GROUP_FAIL'
export const UPDATE_GROUP_RESET = 'UPDATE_GROUP_RESET'
