export const GET_ALL_MISSION_BY_GROUP_REQUEST = 'GET_ALL_MISSION_BY_GROUP_REQUEST'
export const GET_ALL_MISSION_BY_GROUP_SUCCESS = 'GET_ALL_MISSION_BY_GROUP_SUCCESS'
export const GET_ALL_MISSION_BY_GROUP_FAIL = 'GET_ALL_MISSION_BY_GROUP_FAIL'
export const GET_ALL_MISSION_BY_GROUP_RESET = 'GET_ALL_MISSION_BY_GROUP_RESET'

export const ADD_MISSION_REQUEST = 'ADD_MISSION_REQUEST'
export const ADD_MISSION_SUCCESS = 'ADD_MISSION_SUCCESS'
export const ADD_MISSION_FAIL = 'ADD_MISSION_FAIL'
export const ADD_MISSION_RESET = 'ADD_MISSION_RESET'


export const GET_SINGLE_MISSION_REQUEST = 'GET_SINGLE_MISSION_REQUEST'
export const GET_SINGLE_MISSION_SUCCESS = 'GET_SINGLE_MISSION_SUCCESS'
export const GET_SINGLE_MISSION_FAIL = 'GET_SINGLE_MISSION_FAIL'


export const DELETE_MISSION_REQUEST = 'DELETE_MISSION_REQUEST'
export const DELETE_MISSION_SUCCESS = 'DELETE_MISSION_SUCCESS'
export const DELETE_MISSION_FAIL = 'DELETE_MISSION_FAIL'
export const DELETE_MISSION_RESET = 'DELETE_MISSION_RESET'

export const UPDATE_MISSION_REQUEST = 'UPDATE_MISSION_REQUEST'
export const UPDATE_MISSION_SUCCESS = 'UPDATE_MISSION_SUCCESS'
export const UPDATE_MISSION_FAIL = 'UPDATE_MISSION_FAIL'
export const UPDATE_MISSION_RESET = 'UPDATE_MISSION_RESET'


export const GET_COMPLETED_MISSIONS_REQUEST = 'GET_COMPLETED_MISSIONS_REQUEST'
export const GET_COMPLETED_MISSIONS_SUCCESS = 'GET_COMPLETED_MISSIONS_SUCCESS'
export const GET_COMPLETED_MISSIONS_FAIL = 'GET_COMPLETED_MISSIONS_FAIL'

export const GET_UNCOMPLETED_MISSIONS_REQUEST = 'GET_UNCOMPLETED_MISSIONS_REQUEST'
export const GET_UNCOMPLETED_MISSIONS_SUCCESS = 'GET_UNCOMPLETED_MISSIONS_SUCCESS'
export const GET_UNCOMPLETED_MISSIONS_FAIL = 'GET_UNCOMPLETED_MISSIONS_FAIL'