export const GET_ALL_PERSON_REQUEST = 'GET_ALL_PERSON_REQUEST'
export const GET_ALL_PERSON_SUCCESS = 'GET_ALL_PERSON_SUCCESS'
export const GET_ALL_PERSON_FAIL = 'GET_ALL_PERSON_FAIL'

export const ADD_PERSON_REQUEST = 'ADD_PERSON_REQUEST'
export const ADD_PERSON_SUCCESS = 'ADD_PERSON_SUCCESS'
export const ADD_PERSON_FAIL = 'ADD_PERSON_FAIL'
export const ADD_PERSON_RESET = 'ADD_PERSON_RESET'