export const GET_ALL_STEP_REQUEST = 'GET_ALL_STEP_REQUEST'
export const GET_ALL_STEP_SUCCESS = 'GET_ALL_STEP_SUCCESS'
export const GET_ALL_STEP_FAIL = 'GET_ALL_STEP_FAIL'

export const ADD_STEP_REQUEST = 'ADD_STEP_REQUEST'
export const ADD_STEP_SUCCESS = 'ADD_STEP_SUCCESS'
export const ADD_STEP_FAIL = 'ADD_STEP_FAIL'
export const ADD_STEP_RESET = 'ADD_STEP_RESET'


export const DELETE_STEP_REQUEST = 'DELETE_STEP_REQUEST'
export const DELETE_STEP_SUCCESS = 'DELETE_STEP_SUCCESS'
export const DELETE_STEP_FAIL = 'DELETE_STEP_FAIL'
export const DELETE_STEP_RESET = 'DELETE_STEP_RESET'

export const UPDATE_STEP_REQUEST = 'UPDATE_STEP_REQUEST'
export const UPDATE_STEP_SUCCESS = 'UPDATE_STEP_SUCCESS'
export const UPDATE_STEP_FAIL = 'UPDATE_STEP_FAIL'
export const UPDATE_STEP_RESET = 'UPDATE_STEP_RESET'